name: Adapt-Studio
favicon: null
layout_spectrum: 0.8031025922391564
typography_spectrum: 0.06630277051590383
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7135763606056571
  lightness: 0.937127866782248
  saturation: 0.16584819927811623
  rhythmicContrast: 0.7977484420407563
purpose: []
